;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		backward-kill-line
		backward-symbol
		cua-cancel
		cua-paste
		cut-or-backspace
		forward-symbol
		keyboard-escape-quit
		keyboard-quit
		))

(setq mc/cmds-to-run-once
      '(
		mouse-set-region
		))
